CREATE TABLE "program" (
  "program_id" varchar PRIMARY KEY,
  "program_name" varchar NOT NULL,
  "program_credits" int NOT NULL,
  "program_description" text
);

CREATE TABLE "campus" (
  "campus_id" varchar PRIMARY KEY,
  "campus_name" varchar NOT NULL,
  "city" varchar NOT NULL
);

CREATE TABLE "private_details" (
  "private_details_id" varchar PRIMARY KEY,
  "personal_identity_number" char UNIQUE NOT NULL,
  "email" varchar UNIQUE NOT NULL,
  "address" text NOT NULL
);

CREATE TABLE "consultant_company" (
  "consultant_company_id" varchar PRIMARY KEY,
  "company_name" varchar NOT NULL,
  "organization_number" char UNIQUE NOT NULL,
  "f_tax_status" boolean NOT NULL,
  "address" text NOT NULL
);

CREATE TABLE "staff" (
  "staff_id" varchar PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "private_details_id" varchar UNIQUE NOT NULL
);

CREATE TABLE "consultant" (
  "consultant_id" varchar PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "private_details_id" varchar UNIQUE NOT NULL,
  "consultant_company_id" varchar NOT NULL
);

CREATE TABLE "student" (
  "student_id" varchar PRIMARY KEY,
  "first_name" varchar NOT NULL,
  "last_name" varchar NOT NULL,
  "private_details_id" varchar UNIQUE NOT NULL
);

CREATE TABLE "course" (
  "course_id" varchar PRIMARY KEY,
  "program_id" varchar,
  "course_code" varchar NOT NULL,
  "course_name" varchar NOT NULL,
  "course_credits" int NOT NULL,
  "course_description" text
);

CREATE TABLE "class" (
  "class_id" varchar PRIMARY KEY,
  "program_id" varchar,
  "campus_id" varchar NOT NULL,
  "class_name" varchar NOT NULL,
  "class_code" varchar NOT NULL,
  "academic_year" varchar NOT NULL
);

CREATE TABLE "staff_contract" (
  "staff_contract_id" varchar PRIMARY KEY,
  "staff_id" varchar NOT NULL,
  "role" varchar NOT NULL,
  "contract_type" varchar NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" varchar NOT NULL,
  "salary" decimal NOT NULL,
  "campus_id" varchar NOT NULL
);

CREATE TABLE "consultant_contract" (
  "consultant_contract_id" varchar PRIMARY KEY,
  "consultant_id" varchar NOT NULL,
  "role" varchar NOT NULL,
  "contract_type" varchar NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" varchar NOT NULL,
  "hourly_rate" decimal NOT NULL,
  "campus_id" varchar NOT NULL
);

CREATE TABLE "enrollment" (
  "enrollment_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "student_id" varchar NOT NULL,
  "class_id" varchar NOT NULL,
  "enrollment_date" date NOT NULL,
  "status" varchar NOT NULL
);

CREATE TABLE "consultant_teach" (
  "consultant_teach_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "consultant_id" varchar NOT NULL,
  "course_id" varchar NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL
);

CREATE TABLE "program_manager_management" (
  "pm_management_id" varchar PRIMARY KEY,
  "staff_contract_id" varchar NOT NULL,
  "class_id" varchar NOT NULL
);

COMMENT ON COLUMN "program"."program_credits" IS 'CHECK > 0 (enforced in Postgres)';

COMMENT ON COLUMN "private_details"."personal_identity_number" IS '12 digits regex enforced in Postgres';

COMMENT ON COLUMN "consultant_company"."organization_number" IS '10 digits regex enforced in Postgres';

COMMENT ON COLUMN "course"."program_id" IS 'NULL = standalone course';

COMMENT ON COLUMN "course"."course_credits" IS 'CHECK > 0 (enforced in Postgres)';

COMMENT ON COLUMN "class"."program_id" IS 'NULL = standalone class (rule enforced in Postgres)';

COMMENT ON COLUMN "staff_contract"."end_date" IS 'CHECK end_date >= start_date (Postgres)';

COMMENT ON COLUMN "staff_contract"."status" IS 'IN (''ACTIVE'',''ENDED'',''PAUSED'',''PLANNED'') enforced in Postgres';

COMMENT ON COLUMN "consultant_contract"."end_date" IS 'CHECK end_date >= start_date (Postgres)';

COMMENT ON COLUMN "consultant_contract"."status" IS 'IN (''ACTIVE'',''ENDED'',''PAUSED'',''PLANNED'') enforced in Postgres';

COMMENT ON COLUMN "enrollment"."enrollment_date" IS 'DEFAULT CURRENT_DATE in Postgres';

COMMENT ON COLUMN "enrollment"."status" IS 'IN (''ACTIVE'',''COMPLETED'',''WITHDRAWN'') enforced in Postgres';

COMMENT ON COLUMN "consultant_teach"."end_date" IS 'CHECK end_date >= start_date (Postgres)';

ALTER TABLE "staff" ADD FOREIGN KEY ("private_details_id") REFERENCES "private_details" ("private_details_id");

ALTER TABLE "consultant" ADD FOREIGN KEY ("private_details_id") REFERENCES "private_details" ("private_details_id");

ALTER TABLE "student" ADD FOREIGN KEY ("private_details_id") REFERENCES "private_details" ("private_details_id");

ALTER TABLE "consultant" ADD FOREIGN KEY ("consultant_company_id") REFERENCES "consultant_company" ("consultant_company_id");

ALTER TABLE "course" ADD FOREIGN KEY ("program_id") REFERENCES "program" ("program_id");

ALTER TABLE "class" ADD FOREIGN KEY ("program_id") REFERENCES "program" ("program_id");

ALTER TABLE "class" ADD FOREIGN KEY ("campus_id") REFERENCES "campus" ("campus_id");

ALTER TABLE "staff_contract" ADD FOREIGN KEY ("staff_id") REFERENCES "staff" ("staff_id");

ALTER TABLE "staff_contract" ADD FOREIGN KEY ("campus_id") REFERENCES "campus" ("campus_id");

ALTER TABLE "consultant_contract" ADD FOREIGN KEY ("consultant_id") REFERENCES "consultant" ("consultant_id");

ALTER TABLE "consultant_contract" ADD FOREIGN KEY ("campus_id") REFERENCES "campus" ("campus_id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("student_id") REFERENCES "student" ("student_id");

ALTER TABLE "enrollment" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("class_id");

ALTER TABLE "consultant_teach" ADD FOREIGN KEY ("consultant_id") REFERENCES "consultant" ("consultant_id");

ALTER TABLE "consultant_teach" ADD FOREIGN KEY ("course_id") REFERENCES "course" ("course_id");

ALTER TABLE "program_manager_management" ADD FOREIGN KEY ("staff_contract_id") REFERENCES "staff_contract" ("staff_contract_id");

ALTER TABLE "program_manager_management" ADD FOREIGN KEY ("class_id") REFERENCES "class" ("class_id");
